import os
import logging
from datetime import datetime
from app.services.notifications.sms import send_sms
from app.services.notifications.whatsapp import send_whatsapp

logger = logging.getLogger("notifications.service")
logging.basicConfig(level=logging.INFO)

# Load recipient list
DOCTOR_PHONE = os.getenv("DOCTOR_PHONE")
CAREGIVER_PHONE = os.getenv("CAREGIVER_PHONE")
EMERGENCY_PHONE = os.getenv("EMERGENCY_PHONE")

def send_emergency_notifications(
    patient_name: str, 
    score: float, 
    risk: str, 
    reason: str, 
    heart_rate: int, 
    spo2: int, 
    bp: str,
    custom_phone: str = None
) -> dict:
    """
    Formulates and sends real-time emergency alert SMS and WhatsApp notifications
    to all predefined recipients.
    """
    logger.info(f"Triggering emergency notifications workflow for patient {patient_name}...")
    
    # 1. Format SMS Body
    sms_body = (
        f"🚨 AETHER OS EMERGENCY ALERT\n\n"
        f"Patient:\n{patient_name}\n\n"
        f"Risk Level:\n{risk}\n\n"
        f"Risk Score:\n{score}\n\n"
        f"Reason:\n{reason}\n\n"
        f"Vitals\n\n"
        f"❤️ Heart Rate: {heart_rate}\n\n"
        f"🫁 SpO₂: {spo2}\n\n"
        f"🩸 Blood Pressure: {bp}\n\n"
        f"Recommended Action:\n\n"
        f"Immediate medical attention required.\n\n"
        f"Generated by Aether OS."
    )
    
    # 2. Format WhatsApp Body
    whatsapp_body = (
        f"🚨 *Aether OS Emergency Alert*\n\n"
        f"Patient:\n{patient_name}\n\n"
        f"Risk Score:\n{score}\n\n"
        f"Status:\n{risk}\n\n"
        f"Reason\n\n"
        f"{reason}\n\n"
        f"Latest Vitals\n\n"
        f"❤️ HR:\n{heart_rate}\n\n"
        f"🫁 SpO₂:\n{spo2}\n\n"
        f"🩸 BP:\n{bp}\n\n"
        f"Please review immediately."
    )
    
    recipients = {
        "doctor": DOCTOR_PHONE,
        "caregiver": CAREGIVER_PHONE,
        "emergency_contact": EMERGENCY_PHONE
    }
    if custom_phone:
        recipients["custom_phone"] = custom_phone
    
    results = {
        "sms": {},
        "whatsapp": {}
    }
    
    # Send to all defined phone numbers
    for role, phone in recipients.items():
        if not phone:
            logger.warning(f"Recipient phone number not configured for role: {role}")
            results["sms"][role] = "skipped (no phone configured)"
            results["whatsapp"][role] = "skipped (no phone configured)"
            continue
            
        logger.info(f"Sending alerts to {role} ({phone})...")
        
        # Send SMS
        sms_res = send_sms(phone, sms_body)
        results["sms"][role] = sms_res["status"]
        
        # Send WhatsApp
        wa_res = send_whatsapp(phone, whatsapp_body)
        results["whatsapp"][role] = wa_res["status"]
        
    # Check if we had any successful notification dispatch (or skipped dummy values)
    success = any(
        status in ["sent", "skipped"] 
        for channel in ["sms", "whatsapp"] 
        for status in results[channel].values()
    )
    
    final_response = {
        "success": success,
        "sms": "sent" if any(s == "sent" for s in results["sms"].values()) else "failed",
        "whatsapp": "sent" if any(w == "sent" for w in results["whatsapp"].values()) else "failed",
        "timestamp": datetime.utcnow().isoformat(),
        "patient": patient_name,
        "details": results
    }
    
    logger.info(f"Emergency notification workflow finished. Summary: {final_response}")
    return final_response
